# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  twilio_account_sid:  <%= ENV.fetch("SECRET_KEY_BASE", "TWILIO_SID_HERE") %>
  twilio_auth_token:  <%= ENV.fetch("SECRET_KEY_BASE", "TWILIO_AUTH_HERE") %>
  twilio_phone_number:  <%= ENV.fetch("SECRET_KEY_BASE", "TWILIO_PHONE_NUMBER_HERE") %>
  sms_default_number: <%= ENV.fetch("SECRET_KEY_BASE", "DEFAULT_SMS_SEND_NUMBER_HERE") %>

# Environmental secrets are only available for that specific environment.


development:
  secret_key_base: 8f65cbb4d5fa52756423deb605197a44b2e715028fe610532b20061d9eb8042308739e4b950e5f15b1d6fe248d150897876eb8d06484bb92b60e1d13b7193330


test:
  secret_key_base: edc576f7ecbaf58681ef82d5e395d12001c7059ff28bc7d6a26680592f86b96d68cca713ac5353bfcd4778627fa2b58f91f00ec22b03e9b3931fb1d5252e1fbe
  
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
